In [2]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

#데이터 읽어오기
df = pd.read_csv("C:/Users/syjwk/Study_AI/AI_Class/Quiz/2week/mobile.csv", index_col=0)

In [4]:
df

blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
battery_power                                                               
842               0          2.2         0   1       0           7    0.6   
1021              1          0.5         1   0       1          53    0.7   
563               1          0.5         1   2       1          41    0.9   
615               1          2.5         0   0       0          10    0.8   
1821              1          1.2         0  13       1          44    0.6   
...             ...          ...       ...  ..     ...         ...    ...   
794               1          0.5         1   0       1           2    0.8   
1965              1          2.6         1   0       0          39    0.2   
1911              0          0.9         1   1       1          36    0.7   
1512              0          0.9         0   4       1          46    0.1   
510               1          2.0         1   5       1          45    0.9   

               mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
battery_power                                                                  
842                  188        2   2         20       756  2549     9     7   
1021                 136        3   6        905      1988  2631    17     3   
563                  145        5   6       1263      1716  2603    11     2   
615                  131        6   9       1216      1786  2769    16     8   
1821                 141        2  14       1208      1212  1411     8     2   
...                  ...      ...  ..        ...       ...   ...   ...   ...   
794                  106        6  14       1222      1890   668    13     4   
1965                 187        4   3        915      1965  2032    11    10   
1911                 108        8   3        868      1632  3057     9     1   
1512                 145        5   5        336       670   869    18    10   
510                  168        6  16        483       754  3919    19     4   

               talk_time  three_g  touch_screen  wifi  price_range  
battery_power                                                       
842                   19        0             0     1            1  
1021                   7        1             1     0            2  
563                    9        1             1     0            2  
615                   11        1             0     0            2  
1821                  15        1             1     0            1  
...                  ...      ...           ...   ...          ...  
794                   19        1             1     0            0  
1965                  16        1             1     1            2  
1911                   5        1             1     0            3  
1512                  19        1             1     1            0  
510                    2        1             1     1            3  

[2000 rows x 20 columns]

In [6]:
X=df.drop('price_range',axis=1)

X.head()

blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
battery_power                                                               
842               0          2.2         0   1       0           7    0.6   
1021              1          0.5         1   0       1          53    0.7   
563               1          0.5         1   2       1          41    0.9   
615               1          2.5         0   0       0          10    0.8   
1821              1          1.2         0  13       1          44    0.6   

               mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
battery_power                                                                  
842                  188        2   2         20       756  2549     9     7   
1021                 136        3   6        905      1988  2631    17     3   
563                  145        5   6       1263      1716  2603    11     2   
615                  131        6   9       1216      1786  2769    16     8   
1821                 141        2  14       1208      1212  1411     8     2   

               talk_time  three_g  touch_screen  wifi  
battery_power                                          
842                   19        0             0     1  
1021                   7        1             1     0  
563                    9        1             1     0  
615                   11        1             0     0  
1821                  15        1             1     0

In [8]:
y=df['price_range']

y.value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=0)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [14]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.76
[[84 11  0  0]
 [11 61 19  1]
 [ 0 20 62 17]
 [ 0  0 17 97]]


In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.8175
[[ 88   7   0   0]
 [  5  72  15   0]
 [  0  16  67  16]
 [  0   0  14 100]]


In [18]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.8325
[[89  6  0  0]
 [ 7 73 12  0]
 [ 0 14 73 12]
 [ 0  0 16 98]]


In [22]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.655
[[84 10  1  0]
 [17 54 18  3]
 [ 0 25 44 30]
 [ 0  2 32 80]]


In [28]:
print(y_test)

battery_power
1454    3
1092    0
1524    2
1807    2
1086    2
       ..
955     1
809     1
594     0
1673    2
1290    1
Name: price_range, Length: 400, dtype: int64
